version: '3.9'

services:
  api:
    build:
      context: https://github.com/gustavorh/gatekeeper-backend.git
      # usa el stage prod por defecto del Dockerfile
    container_name: gatekeeper-backend
    environment:
      NODE_ENV: production
      PORT: 3000
      DATABASE_URL: ${DATABASE_URL}
      JWT_SECRET: ${JWT_SECRET}
      FRONTEND_URL: ${FRONTEND_URL}
    ports:
      - '3000:3000'
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3000/health']
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    networks: [gatekeeper_net]
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  gatekeeper_net:
    external: true
