version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend
    environment:
      NODE_ENV: production
      PORT: 3000
      # ---- ENV de tu app ----
      DATABASE_URL: ${DATABASE_URL} # apunta al MySQL 10.0.40.253
      JWT_SECRET: ${JWT_SECRET}
    # Publica el puerto si accederás directo; quítalo si usarás Traefik/NPM
    ports:
      - '3000:3000'
    # Healthcheck contra /health (ver snippet de main.ts más abajo)
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:3000/health']
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
    command:
      [
        'sh',
        '-lc',
        "if [ -f dist/main.js ]; then node dist/main.js; elif [ -f dist/src/main.js ]; then node dist/src/main.js; else echo 'No encuentro el entrypoint; muestro dist:'; ls -R dist; exit 1; fi",
      ]
    # --- Labels Traefik (opcional) ---
    # labels:
    #   - "traefik.enable=true"
    #   - "traefik.http.routers.gatekeeper.rule=Host(`api.gustavorh.com`)"
    #   - "traefik.http.routers.gatekeeper.entrypoints=websecure"
    #   - "traefik.http.routers.gatekeeper.tls.certresolver=letsencrypt"
    #   - "traefik.http.services.gatekeeper.loadbalancer.server.port=3000"
  frontend:
    build:
      context: https://github.com/gustavorh/gatekeeper-frontend.git#main
      dockerfile: Dockerfile
      args:
        # IMPORTANTE: esto se inyecta en build-time de Next.js
        NEXT_PUBLIC_API_URL: ${NEXT_PUBLIC_API_URL}
    container_name: frontend
    environment:
      NODE_ENV: production
      PORT: 8000 # Next.js escuchará en 8000
    depends_on:
      - api # tu servicio backend
    ports:
      - '8000:8000' # expone el frontend en el host 8000
    healthcheck:
      test: ['CMD', 'wget', '-qO-', 'http://localhost:8000/']
      interval: 10s
      timeout: 5s
      retries: 10
    restart: unless-stopped
